name = "embediframe"
type = "javascript"
account_id = "dc642e62b4202987af42afb3a2aadb25"
zone_id = "4618ae3dc797aca34490a22f06ecaba0"
main = "assets/js/iframe-viewer.js"
compatibility_date = "2024-04-17"

routes = [
  "https://www.asibuka.com/*"
]