name: Deploy Cloudflare Worker 2

on:
  push:
    branches: [main]
    paths:
      - "assets/workers/worker-2/**"
      - ".github/workflows/cloudflare-worker-2.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: assets/workers/worker-2