name: Deploy Cloudflare Worker

on:
  push:
    branches: [main]
    paths:
      - "assets/workers/worker-1/**"
      - ".github/workflows/cloudflare-worker-1.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Worker

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: assets/workers/worker-1
