name: Deploy Cloudflare Worker

on:
  push:
    branches: [main] # change this if needed
    paths:
      - "src/**" # where your Worker code is
      - "wrangler.toml"
      - ".github/workflows/deploy-worker.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Worker

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
