name: Build and Deploy AMP

on:
  push:
    branches:
      - main  # or 'master' depending on your repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build AMP site
        run: bundle exec jekyll build --config _config.yml,_config.amp.yml -d _site/amp

      - name: Upload AMP artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: _site/amp

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2